### ISSUE TITLE
crypto.py encode error

### ISSUE THREAD

**Issue by PetzJohannes** [tildaslash/RatticWeb#407]
Hello,

the following error is displayed in my http error_log.
I am using RatticWeb v1.3.1 with apache on CentOS 6.

Can you give me anything to fix this issue?
Regards Johannes

[Wed Oct 28 14:17:19 2015] [error] 2015-10-28 14:17:19,612 [ERROR] Internal Server Error: /
[Wed Oct 28 14:17:19 2015] [error] Traceback (most recent call last):
[Wed Oct 28 14:17:19 2015] [error]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 201, in get_response
[Wed Oct 28 14:17:19 2015] [error]     response = middleware_method(request, response)
[Wed Oct 28 14:17:19 2015] [error]   File "/usr/lib/python2.6/site-packages/django_user_sessions-0.1.3-py2.6.egg/user_sessions/middleware.py", line 46, in process_response
[Wed Oct 28 14:17:19 2015] [error]     request.session.save()
[Wed Oct 28 14:17:19 2015] [error]   File "/usr/lib/python2.6/site-packages/django_user_sessions-0.1.3-py2.6.egg/user_sessions/backends/db.py", line 69, in save
[Wed Oct 28 14:17:19 2015] [error]     session_data=self.encode(self._get_session(no_load=must_create)),
[Wed Oct 28 14:17:19 2015] [error]   File "/usr/lib/python2.6/site-packages/django/contrib/sessions/backends/base.py", line 88, in encode
[Wed Oct 28 14:17:19 2015] [error]     hash = self._hash(serialized)
[Wed Oct 28 14:17:19 2015] [error]   File "/usr/lib/python2.6/site-packages/django/contrib/sessions/backends/base.py", line 83, in _hash
[Wed Oct 28 14:17:19 2015] [error]     return salted_hmac(key_salt, value).hexdigest()
[Wed Oct 28 14:17:19 2015] [error]   File "/usr/lib/python2.6/site-packages/django/utils/crypto.py", line 44, in salted_hmac
[Wed Oct 28 14:17:19 2015] [error]     key = hashlib.sha1((key_salt + secret).encode('utf-8')).digest()
[Wed Oct 28 14:17:19 2015] [error] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)

**Comment by PetzJohannes** [comment]
Okay I solved it.
The Problem was the "secretkey" option on "ratticweb" section in local.cfg file.
The ninth character was a §. I deleted the char and all works brilliant!

At first I thought the problem is in a crypt library, so I searched in the wrong direction.

May anyone else has the same issue and this helps.

This issue can now be closed.
