### ISSUE TITLE
Error on manage.py syncdb --noinput

### ISSUE THREAD

**Issue by Nontenda** [tildaslash/RatticWeb#416]
Hi,

I'm running a Fedora 24 with Python 2.7.
I've installed all requirements (pip install -r requirements-*) but when I try to make "manage.py syncdb --noinput" I got this traceback :

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 242, in     run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 68, in     handle_noargs
    migrations = migration.Migrations(app_label)
  File "/usr/lib/python2.7/site-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass,     self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/usr/lib/python2.7/site-packages/south/migration/base.py", line 90, in __init__
self.set_application(application, force_creation, verbose_creation)
  File "/usr/lib/python2.7/site-packages/south/migration/base.py", line 154, in set_application
    module = importlib.import_module(self.migrations_module())
  File "/usr/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/kombu/transport/django/migrations/__init__.py", line 16, in     <module>
    raise ImproperlyConfigured(SOUTH_ERROR_MESSAGE)
django.core.exceptions.ImproperlyConfigured:
For South support, customize the SOUTH_MIGRATION_MODULES setting
to point to the correct migrations module:
    SOUTH_MIGRATION_MODULES = {
        'kombu_transport_django': 'kombu.transport.django.south_migrations',
    }
```

Thank you very much for your help.

**Comment by Nontenda** [comment]
Resolved with this commit : 
https://github.com/csakoda/RatticWeb/commit/6758574e917cde2a9efd42f6cb1312f9819f04ff
