### ISSUE TITLE
Error in Rattic

### ISSUE THREAD

**Issue by hamedchoobin** [tildaslash/RatticWeb#458]
Hi
I get this errors:

[Mon Dec 12 10:25:18.022899 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 409, in has_results
[Mon Dec 12 10:25:18.022905 2016] [:error] [pid 8145:tid 140603538032384]     return bool(compiler.execute_sql(SINGLE))
[Mon Dec 12 10:25:18.022934 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
[Mon Dec 12 10:25:18.022942 2016] [:error] [pid 8145:tid 140603538032384]     cursor.execute(sql, params)
[Mon Dec 12 10:25:18.022949 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
[Mon Dec 12 10:25:18.022955 2016] [:error] [pid 8145:tid 140603538032384]     return self.cursor.execute(sql, params)
[Mon Dec 12 10:25:18.022962 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
[Mon Dec 12 10:25:18.022968 2016] [:error] [pid 8145:tid 140603538032384]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Mon Dec 12 10:25:18.022975 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
[Mon Dec 12 10:25:18.022981 2016] [:error] [pid 8145:tid 140603538032384]     return self.cursor.execute(sql, params)
[Mon Dec 12 10:25:18.022987 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
[Mon Dec 12 10:25:18.022994 2016] [:error] [pid 8145:tid 140603538032384]     return self.cursor.execute(query, args)
[Mon Dec 12 10:25:18.023000 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
[Mon Dec 12 10:25:18.023006 2016] [:error] [pid 8145:tid 140603538032384]     self.errorhandler(self, exc, value)
[Mon Dec 12 10:25:18.023013 2016] [:error] [pid 8145:tid 140603538032384]   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
[Mon Dec 12 10:25:18.023019 2016] [:error] [pid 8145:tid 140603538032384]     raise errorclass, errorvalue
[Mon Dec 12 10:25:18.023025 2016] [:error] [pid 8145:tid 140603538032384] ProgrammingError: (1146, "Table 'hami_database.user_sessions_session' doesn't exist")
[Mon Dec 12 10:25:19.619155 2016] [:error] [pid 8145:tid 140603504461568] 2016-12-12 10:25:19,618 [ERROR] Internal Server Error: /i18n/setlang/
[Mon Dec 12 10:25:19.619210 2016] [:error] [pid 8145:tid 140603504461568] Traceback (most recent call last):
[Mon Dec 12 10:25:19.619220 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 199, in get_response
[Mon Dec 12 10:25:19.619227 2016] [:error] [pid 8145:tid 140603504461568]     response = middleware_method(request, response)
[Mon Dec 12 10:25:19.619235 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/user_sessions/middleware.py", line 46, in process_response
[Mon Dec 12 10:25:19.619242 2016] [:error] [pid 8145:tid 140603504461568]     request.session.save()
[Mon Dec 12 10:25:19.619248 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/user_sessions/backends/db.py", line 68, in save
[Mon Dec 12 10:25:19.619255 2016] [:error] [pid 8145:tid 140603504461568]     session_key=self._get_or_create_session_key(),
[Mon Dec 12 10:25:19.619262 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 153, in _get_or_create_session_key
[Mon Dec 12 10:25:19.619269 2016] [:error] [pid 8145:tid 140603504461568]     self._session_key = self._get_new_session_key()
[Mon Dec 12 10:25:19.619276 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 147, in _get_new_session_key
[Mon Dec 12 10:25:19.619283 2016] [:error] [pid 8145:tid 140603504461568]     if not self.exists(session_key):
[Mon Dec 12 10:25:19.619289 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/user_sessions/backends/db.py", line 44, in exists
[Mon Dec 12 10:25:19.619318 2016] [:error] [pid 8145:tid 140603504461568]     return Session.objects.filter(session_key=session_key).exists()
[Mon Dec 12 10:25:19.619327 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 515, in exists
[Mon Dec 12 10:25:19.619334 2016] [:error] [pid 8145:tid 140603504461568]     return self.query.has_results(using=self.db)
[Mon Dec 12 10:25:19.619340 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 409, in has_results
[Mon Dec 12 10:25:19.619347 2016] [:error] [pid 8145:tid 140603504461568]     return bool(compiler.execute_sql(SINGLE))
[Mon Dec 12 10:25:19.619353 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
[Mon Dec 12 10:25:19.619360 2016] [:error] [pid 8145:tid 140603504461568]     cursor.execute(sql, params)
[Mon Dec 12 10:25:19.619366 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
[Mon Dec 12 10:25:19.619373 2016] [:error] [pid 8145:tid 140603504461568]     return self.cursor.execute(sql, params)
[Mon Dec 12 10:25:19.619379 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
[Mon Dec 12 10:25:19.619386 2016] [:error] [pid 8145:tid 140603504461568]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Mon Dec 12 10:25:19.619392 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
[Mon Dec 12 10:25:19.619399 2016] [:error] [pid 8145:tid 140603504461568]     return self.cursor.execute(sql, params)
[Mon Dec 12 10:25:19.619405 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
[Mon Dec 12 10:25:19.619412 2016] [:error] [pid 8145:tid 140603504461568]     return self.cursor.execute(query, args)
[Mon Dec 12 10:25:19.619418 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
[Mon Dec 12 10:25:19.619425 2016] [:error] [pid 8145:tid 140603504461568]     self.errorhandler(self, exc, value)
[Mon Dec 12 10:25:19.619431 2016] [:error] [pid 8145:tid 140603504461568]   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
[Mon Dec 12 10:25:19.619438 2016] [:error] [pid 8145:tid 140603504461568]     raise errorclass, errorvalue
[Mon Dec 12 10:25:19.619444 2016] [:error] [pid 8145:tid 140603504461568] ProgrammingError: (1146, "Table 'xxx_database.user_sessions_session' doesn't exist")

How i can solve it?

**Comment by hamedchoobin** [comment]
no any one?????????????

**Comment by yarokifor** [comment]
This project is dead. [Here](https://twitter.com/RatticDB/status/656970187787276288) is their latest twitter status.

**Comment by VidmantasNsoft** [comment]
user_sessions_session does exist? do you create sessions for user?

**Comment by hamedchoobin** [comment]
what is the best distribution for this app?

**Comment by VidmantasNsoft** [comment]
i used ubuntu

**Comment by hamedchoobin** [comment]
i following this instruction
https://github.com/tildaslash/RatticWeb/wiki/Installing

but its command not apply any change to my database...
how i can create any session in my database? this command work but not any apply to database

**Comment by Eh1k0** [comment]
Table 'xxx_database.user_sessions_session' error Is pretty clear.  Can you please perform syncdb/migratedb?
